---
networks:
  backend:
    external: true
services:
  compiler:
    container_name: terminal-stream 
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3003
    restart: unless-stopped
    networks:
        - backend
