---
services:
  compiler:
    container_name: compiler
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 3002
      DOCKER_HOST: 10.10.10.246
    restart: unless-stopped
    network_mode: "host"
